const kriteria = [
  {
    id_kriteria: 1,
    nama_kriteria: "Tes Tulis",
    deskripsi_kriteria: "Uji tulis untuk mengukur kemampuan menulis",
    bobot: 1.0,
    jenis_kriteria: "BENEFIT",
  },
  {
    id_kriteria: 2,
    nama_kriteria: "Tes Praktek",
    deskripsi_kriteria: "Uji coba praktis untuk mengukur kemampuan kerja",
    bobot: 1.0,
    jenis_kriteria: "BENEFIT",
  },
  {
    id_kriteria: 3,
    nama_kriteria: "Tes Teknis",
    deskripsi_kriteria: "Uji kemampuan teknis khusus",
    bobot: 0.5,
    jenis_kriteria: "BENEFIT",
  },
  {
    id_kriteria: 4,
    nama_kriteria: "Tes Psikotes",
    deskripsi_kriteria: "Uji psikologis untuk mengevaluasi kepribadian",
    bobot: 1.0,
    jenis_kriteria: "BENEFIT",
  },
  {
    id_kriteria: 5,
    nama_kriteria: "Pengalaman",
    deskripsi_kriteria: "Penilaian terhadap pengalaman kerja sebelumnya",
    bobot: 0.1,
    jenis_kriteria: "BENEFIT",
  },
  {
    id_kriteria: 6,
    nama_kriteria: "Pendidikan",
    deskripsi_kriteria: "Evaluasi tingkat pendidikan formal",
    bobot: 0.2,
    jenis_kriteria: "BENEFIT",
  },
  {
    id_kriteria: 7,
    nama_kriteria: "Komunikasi",
    deskripsi_kriteria: "Penilaian kemampuan berkomunikasi",
    bobot: 0.3,
    jenis_kriteria: "BENEFIT",
  },
  {
    id_kriteria: 8,
    nama_kriteria: "Minat",
    deskripsi_kriteria: "Evaluasi minat dan motivasi",
    bobot: 0.1,
    jenis_kriteria: "BENEFIT",
  },
  {
    id_kriteria: 9,
    nama_kriteria: "Pengetahuan Organisasi",
    deskripsi_kriteria: "Pemahaman tentang struktur organisasi perusahaan",
    bobot: 0.1,
    jenis_kriteria: "BENEFIT",
  },
  {
    id_kriteria: 10,
    nama_kriteria: "Kerja Sama",
    deskripsi_kriteria: "Kemampuan bekerja dalam tim",
    bobot: 0.1,
    jenis_kriteria: "BENEFIT",
  },
  {
    id_kriteria: 11,
    nama_kriteria: "Inisiatif",
    deskripsi_kriteria: "Kemampuan mengambil tindakan proaktif",
    bobot: 0.1,
    jenis_kriteria: "BENEFIT",
  },
  {
    id_kriteria: 12,
    nama_kriteria: "Manajemen Waktu",
    deskripsi_kriteria: "Kemampuan mengatur waktu",
    bobot: 0.1,
    jenis_kriteria: "BENEFIT",
  },
];

module.exports = { kriteria };
